---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: github-instavote
  namespace: instavote
spec:
  address: https://github.com/danilogranadosg/instavote-deploy.git
  secretRef:
    name: github-token
  type: github
